// Autogenerated main.js file

require('jsb_cocos2d_constants.js');
require('jsb_cocos2d.js');
require('jsb_cocos2d_extension.js');
require('jsb_opengl_constants.js');
require('jsb_opengl.js');
require('jsb_cocosbuilder.js');
require('jsb_sys.js');

require("jsb_binpack_auto_api.js");
require("binpack_test.js");

require("ts_utils.js");
require("test_binpack_layer.js");
function main()
{
	//cc.FileUtils.getInstance().loadFilenameLookup("fileLookup.plist");
    //cc.Texture2D.setDefaultAlphaPixelFormat(6);
	var director = cc.Director.getInstance();
    var scene = cc.Scene.create();
    
    var winSize = director.getWinSize();
    
    var sHeight = 500;
    var bklayer = cc.Layer.create();
    
    var layerSize = cc.size(winSize.width*3,sHeight);
    var packLayer =  new TestBinPackController(layerSize);
    
    var scrollview = cc.ScrollView.create(cc.size(winSize.width,sHeight),packLayer);
    scrollview.setDirection(cc.SCROLLVIEW_DIRECTION_HORIZONTAL);
    scrollview.updateInset();
    
    bklayer.addChild(scrollview);
    scrollview.setPosition(cc.p(0,(winSize.height-sHeight)/2));
    scrollview.setAnchorPoint(cc.p(0,0));   
    
    //scrollview.getContainer().addChild(packLayer);
    
    cc.log("TestBinPackController");
    scene.addChild(bklayer);
    bklayer.setAnchorPoint(cc.p(0,0));
   // bklayer.setPosition(cc.p(winSize.width/2,winSize.height/2));
    
    var runningScene = director.getRunningScene();
    if (runningScene === null) director.runWithScene(scene);
    else director.replaceScene(scene);
    
 
}
main();